[package]
name = "vex-pages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
memmap2 = "^0.5"
parking_lot = "0.11.2"
timely = "0.12.0"